# Use official Node image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Build Nuxt app
RUN npm run build

# Expose port
EXPOSE 3000

# Run Nuxt in production
CMD ["npm", "run", "start"]
